#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


#Rodar php stant

./vendor/bin/phpstan

if [ $? -ne 0 ]; then

    echo "Opa! Deu ruim aqui com PHPSTAN. Arrume antes de continuar... =/";

    exit 1;

fi;

#Executar os testes

php artisan test --parallel | php

if [ $? -ne 0 ]; then

    echo "Opa! Deu ruim aqui com algum teste. Arrume antes de continuar... =/";

    exit 1;

fi;


exit 0;
